import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/sonner"
import { NavigationBar } from "@/components/Nav-bar"
import { UserProvider } from "@/context/userContext"
import AuthStateManager from "./highLevelComponent"
import GoogleTranslate from "@/components/google-translate"
import PreventNavigation from "@/components/preventNavigation"
import { GoogleTranslateProvider } from "@/context/googleTranslateContext"
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <GoogleTranslateProvider>
            <GoogleTranslate />
            <PreventNavigation />
            <main>
              <UserProvider>
                <AuthStateManager>
                  {children}
                  <NavigationBar />
                </AuthStateManager>
              </UserProvider>
            </main>

            <Toaster />
          </GoogleTranslateProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
